# Generated by Django 3.2.24 on 2024-03-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userimagepredictionmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('emotion', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'db_table': 'userimagepredictionmodel',
            },
        ),
    ]
